group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
overflow_delimited_expr = true
spaces_around_ranges = true
use_field_init_shorthand = true
